---

- name: create .ssh directory if it doens't exist
  file:
    path: ~{{ item.UserName }}/.ssh
    state:  directory
    mode: 0700
  become_user: "{{ item.UserName }}"
  with_items: "{{ Users }}"
  loop_control:
    label: "{{ item.UserName }}"

- name: Build .ssh/config file and copy it into .ssh/config
  template:
    src:  config.j2
    dest: /home/{{UserName}}/.ssh/config
    backup: no
    mode: 0644
  become_user: "{{ item.UserName }}"
  with_items: "{{ Users }}"
  loop_control:
    label: "{{ item.UserName }}"